export const SEARCH_KEY_CACHE_TTL = process.env.SEARCH_KEY_CACHE_EXPIRY === undefined ? 5 : +process.env.SEARCH_KEY_CACHE_EXPIRY; // 5 seconds
export const SEARCH_KEY_CACHE_NO_TTl = -1

export const MAX_WORD_LENGTH = 55;

export const KOGNITOS_COUNTERS_USER_VERSION_1_KEY = 'v1'
export const KOGNITOS_COUNTERS_USER_VERSION_2_KEY = 'v2'
export const KOGNITOS_COUNTERS_USER_VERSION_3_KEY = 'v3'
export const KOGNITOS_COUNTERS_USER_INPUT_TOPIC_PREFIX = 'kognitos-counters-versioned-user-input'
export const KOGNITOS_COUNTERS_USER_INPUT_TOPIC_V1 = `${KOGNITOS_COUNTERS_USER_INPUT_TOPIC_PREFIX}-${KOGNITOS_COUNTERS_USER_VERSION_1_KEY}`
export const KOGNITOS_COUNTERS_USER_INPUT_TOPIC_V2 = `${KOGNITOS_COUNTERS_USER_INPUT_TOPIC_PREFIX}-${KOGNITOS_COUNTERS_USER_VERSION_2_KEY}`
export const KOGNITOS_COUNTERS_USER_INPUT_TOPIC_V3 = `${KOGNITOS_COUNTERS_USER_INPUT_TOPIC_PREFIX}-${KOGNITOS_COUNTERS_USER_VERSION_3_KEY}`

export const KOGNITOS_COUNTERS_USER_INPUT_CONSUMER_TOPICS = new RegExp(`${KOGNITOS_COUNTERS_USER_INPUT_TOPIC_PREFIX}.*`)
export const KOGNITOS_COUNTERS_CONSUMER_GROUP_ID = 'kognitos-counters-versioned-user-input-asyn-handler-1'
